//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.11 at 09:59:37 PM CST 
//


package com.tradeo.exp.common.message.EXP304;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sw.busi.swspl.entity.message.common.EXP304 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sw.busi.swspl.entity.message.common.EXP304
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EXP304 }
     * 
     */
    public EXP304 createEXP304() {
        return new EXP304();
    }

    /**
     * Create an instance of {@link Package }
     * 
     */
    public Package createPackage() {
        return new Package();
    }

    /**
     * Create an instance of {@link Package.DataInfo }
     * 
     */
    public Package.DataInfo createPackageDataInfo() {
        return new Package.DataInfo();
    }

    /**
     * Create an instance of {@link Package.DataInfo.SignedData }
     * 
     */
    public Package.DataInfo.SignedData createPackageDataInfoSignedData() {
        return new Package.DataInfo.SignedData();
    }

    /**
     * Create an instance of {@link EXP304 .EntryHead }
     * 
     */
    public EXP304 .EntryHead createEXP304EntryHead() {
        return new EXP304 .EntryHead();
    }

    /**
     * Create an instance of {@link EXP304 .EntryList }
     * 
     */
    public EXP304 .EntryList createEXP304EntryList() {
        return new EXP304 .EntryList();
    }

    /**
     * Create an instance of {@link EXP304 .EntryDocu }
     * 
     */
    public EXP304 .EntryDocu createEXP304EntryDocu() {
        return new EXP304 .EntryDocu();
    }

    /**
     * Create an instance of {@link EnvelopInfo }
     * 
     */
    public EnvelopInfo createEnvelopInfo() {
        return new EnvelopInfo();
    }

    /**
     * Create an instance of {@link Package.DataInfo.SignedData.Data }
     * 
     */
    public Package.DataInfo.SignedData.Data createPackageDataInfoSignedDataData() {
        return new Package.DataInfo.SignedData.Data();
    }

}
