//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.11 at 09:59:42 PM CST 
//


package com.tradeo.exp.common.message.EXP310;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "entryDuty"
})
@XmlRootElement(name = "EXP310")
public class EXP310 {

    @XmlElement(name = "EntryDuty", required = true)
    protected EXP310 .EntryDuty entryDuty;

    /**
     * Gets the value of the entryDuty property.
     * 
     * @return
     *     possible object is
     *     {@link EXP310 .EntryDuty }
     *     
     */
    public EXP310 .EntryDuty getEntryDuty() {
        return entryDuty;
    }

    /**
     * Sets the value of the entryDuty property.
     * 
     * @param value
     *     allowed object is
     *     {@link EXP310 .EntryDuty }
     *     
     */
    public void setEntryDuty(EXP310 .EntryDuty value) {
        this.entryDuty = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="BillNo">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="32"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="AssBillNo">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="32"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="IEFlag">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="EntryId">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;length value="18"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="OpTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="RealDuty">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="0"/>
     *               &lt;maxLength value="20"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RealTax">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="0"/>
     *               &lt;maxLength value="20"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RealReg">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="0"/>
     *               &lt;maxLength value="20"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RealAnti">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="0"/>
     *               &lt;maxLength value="20"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RealRsv1">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="0"/>
     *               &lt;maxLength value="20"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RealRsv2">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="0"/>
     *               &lt;maxLength value="20"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RealNcad">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="0"/>
     *               &lt;maxLength value="20"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "billNo",
        "assBillNo",
        "ieFlag",
        "entryId",
        "opTime",
        "realDuty",
        "realTax",
        "realReg",
        "realAnti",
        "realRsv1",
        "realRsv2",
        "realNcad"
    })
    public static class EntryDuty {

        @XmlElement(name = "BillNo", required = true)
        protected String billNo;
        @XmlElement(name = "AssBillNo", required = true)
        protected String assBillNo;
        @XmlElement(name = "IEFlag", required = true)
        protected String ieFlag;
        @XmlElement(name = "EntryId", required = true)
        protected String entryId;
        @XmlElement(name = "OpTime", required = true)
        protected String opTime;
        @XmlElement(name = "RealDuty", required = true)
        protected String realDuty;
        @XmlElement(name = "RealTax", required = true)
        protected String realTax;
        @XmlElement(name = "RealReg", required = true)
        protected String realReg;
        @XmlElement(name = "RealAnti", required = true)
        protected String realAnti;
        @XmlElement(name = "RealRsv1", required = true)
        protected String realRsv1;
        @XmlElement(name = "RealRsv2", required = true)
        protected String realRsv2;
        @XmlElement(name = "RealNcad", required = true)
        protected String realNcad;

        /**
         * Gets the value of the billNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBillNo() {
            return billNo;
        }

        /**
         * Sets the value of the billNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBillNo(String value) {
            this.billNo = value;
        }

        /**
         * Gets the value of the assBillNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAssBillNo() {
            return assBillNo;
        }

        /**
         * Sets the value of the assBillNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAssBillNo(String value) {
            this.assBillNo = value;
        }

        /**
         * Gets the value of the ieFlag property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIEFlag() {
            return ieFlag;
        }

        /**
         * Sets the value of the ieFlag property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIEFlag(String value) {
            this.ieFlag = value;
        }

        /**
         * Gets the value of the entryId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEntryId() {
            return entryId;
        }

        /**
         * Sets the value of the entryId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEntryId(String value) {
            this.entryId = value;
        }

        /**
         * Gets the value of the opTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOpTime() {
            return opTime;
        }

        /**
         * Sets the value of the opTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOpTime(String value) {
            this.opTime = value;
        }

        /**
         * Gets the value of the realDuty property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRealDuty() {
            return realDuty;
        }

        /**
         * Sets the value of the realDuty property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRealDuty(String value) {
            this.realDuty = value;
        }

        /**
         * Gets the value of the realTax property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRealTax() {
            return realTax;
        }

        /**
         * Sets the value of the realTax property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRealTax(String value) {
            this.realTax = value;
        }

        /**
         * Gets the value of the realReg property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRealReg() {
            return realReg;
        }

        /**
         * Sets the value of the realReg property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRealReg(String value) {
            this.realReg = value;
        }

        /**
         * Gets the value of the realAnti property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRealAnti() {
            return realAnti;
        }

        /**
         * Sets the value of the realAnti property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRealAnti(String value) {
            this.realAnti = value;
        }

        /**
         * Gets the value of the realRsv1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRealRsv1() {
            return realRsv1;
        }

        /**
         * Sets the value of the realRsv1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRealRsv1(String value) {
            this.realRsv1 = value;
        }

        /**
         * Gets the value of the realRsv2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRealRsv2() {
            return realRsv2;
        }

        /**
         * Sets the value of the realRsv2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRealRsv2(String value) {
            this.realRsv2 = value;
        }

        /**
         * Gets the value of the realNcad property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRealNcad() {
            return realNcad;
        }

        /**
         * Sets the value of the realNcad property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRealNcad(String value) {
            this.realNcad = value;
        }

    }

}
