//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.12 at 02:21:22 PM CST 
//


package com.tradeo.exp.common.message.EXP302;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EntryHead">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PreEntryId">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="18"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="OpType">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="3"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="BillNo">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="32"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="AssBillNo">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="32"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="IEFlag">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;length value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="EntryId">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="18"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="OpTime" type="{http://www.chinaport.gov.cn/exp}yyyyMMddHHmmsszzz"/>
 *                   &lt;element name="OpResult">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="2"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Notes">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="4096"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "entryHead"
})
@XmlRootElement(name = "EXP302")
public class EXP302 {

    @XmlElement(name = "EntryHead", required = true)
    protected EXP302 .EntryHead entryHead;

    /**
     * Gets the value of the entryHead property.
     * 
     * @return
     *     possible object is
     *     {@link EXP302 .EntryHead }
     *     
     */
    public EXP302 .EntryHead getEntryHead() {
        return entryHead;
    }

    /**
     * Sets the value of the entryHead property.
     * 
     * @param value
     *     allowed object is
     *     {@link EXP302 .EntryHead }
     *     
     */
    public void setEntryHead(EXP302 .EntryHead value) {
        this.entryHead = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PreEntryId">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="18"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="OpType">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="3"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="BillNo">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="32"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="AssBillNo">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="32"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="IEFlag">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;length value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="EntryId">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="18"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="OpTime" type="{http://www.chinaport.gov.cn/exp}yyyyMMddHHmmsszzz"/>
     *         &lt;element name="OpResult">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="2"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Notes">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="4096"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "preEntryId",
        "opType",
        "billNo",
        "assBillNo",
        "ieFlag",
        "entryId",
        "opTime",
        "opResult",
        "notes"
    })
    public static class EntryHead {

        @XmlElement(name = "PreEntryId", required = true)
        protected String preEntryId;
        @XmlElement(name = "OpType", required = true)
        protected String opType;
        @XmlElement(name = "BillNo", required = true)
        protected String billNo;
        @XmlElement(name = "AssBillNo", required = true)
        protected String assBillNo;
        @XmlElement(name = "IEFlag", required = true)
        protected String ieFlag;
        @XmlElement(name = "EntryId", required = true)
        protected String entryId;
        @XmlElement(name = "OpTime", required = true)
        protected String opTime;
        @XmlElement(name = "OpResult", required = true)
        protected String opResult;
        @XmlElement(name = "Notes", required = true)
        protected String notes;

        /**
         * Gets the value of the preEntryId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPreEntryId() {
            return preEntryId;
        }

        /**
         * Sets the value of the preEntryId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPreEntryId(String value) {
            this.preEntryId = value;
        }

        /**
         * Gets the value of the opType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOpType() {
            return opType;
        }

        /**
         * Sets the value of the opType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOpType(String value) {
            this.opType = value;
        }

        /**
         * Gets the value of the billNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBillNo() {
            return billNo;
        }

        /**
         * Sets the value of the billNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBillNo(String value) {
            this.billNo = value;
        }

        /**
         * Gets the value of the assBillNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAssBillNo() {
            return assBillNo;
        }

        /**
         * Sets the value of the assBillNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAssBillNo(String value) {
            this.assBillNo = value;
        }

        /**
         * Gets the value of the ieFlag property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIEFlag() {
            return ieFlag;
        }

        /**
         * Sets the value of the ieFlag property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIEFlag(String value) {
            this.ieFlag = value;
        }

        /**
         * Gets the value of the entryId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEntryId() {
            return entryId;
        }

        /**
         * Sets the value of the entryId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEntryId(String value) {
            this.entryId = value;
        }

        /**
         * Gets the value of the opTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOpTime() {
            return opTime;
        }

        /**
         * Sets the value of the opTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOpTime(String value) {
            this.opTime = value;
        }

        /**
         * Gets the value of the opResult property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOpResult() {
            return opResult;
        }

        /**
         * Sets the value of the opResult property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOpResult(String value) {
            this.opResult = value;
        }

        /**
         * Gets the value of the notes property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNotes() {
            return notes;
        }

        /**
         * Sets the value of the notes property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNotes(String value) {
            this.notes = value;
        }

    }

}
